### ISSUE TITLE
Create a simple view that shows tests in order of number of failures

### ISSUE THREAD

**Issue by mrobinson** [servo/intermittent-tracker#15]
This bug is about showing a simple view of the tests that flake the most. We don't need to show all tests, but maybe it would be good to show the top 100 tests and the number of times they had unexpected results.

**Comment by chickenleaf** [comment]
are we to modify the index.html or make a new one exclusively for this?

**Comment by mrobinson** [comment]
> are we to modify the index.html or make a new one exclusively for this?

I think it would be best to create a new HTML file with the view.

**Comment by chickenleaf** [comment]
> > are we to modify the index.html or make a new one exclusively for this?
> 
> I think it would be best to create a new HTML file with the view.

I have built a simple view. Do I send in a github link here to the file?

**Comment by mrobinson** [comment]
> I have built a simple view. Do I send in a github link here to the file?

Please open a PR for this view. Thanks!

**Comment by chickenleaf** [comment]
> > I have built a simple view. Do I send in a github link here to the file?
> 
> Please open a PR for this view. Thanks!

oh no but i used a completely new repository different from this repository. it is just requesting data from https://build.servo.org/intermittent-tracker/dashboard/attempts

**Comment by mrobinson** [comment]
> oh no but i used a completely new repository different from this repository. it is just requesting data from https://build.servo.org/intermittent-tracker/dashboard/attempts

The data that needs to be displayed for this page is too probably too large to be something fetched remotely. The new view should be based on the existing on in this repository, but doing a different set of database queries to get the tests that are the flakiest.

**Comment by mrobinson** [comment]
Apologies for the delay. Here is data you can use for testing your changes when implementing this view:

[intermittent-tracker.zip](https://github.com/servo/intermittent-tracker/files/14568586/intermittent-tracker.zip)
