### ISSUE TITLE
Add a link to the corresponding GitHub issue for each test listed in the `most-flaky` view

### ISSUE THREAD

**Issue by mrobinson** [servo/intermittent-tracker#17]
The `most-flaky` view lists each test, but it would be useful to have a link to the corresponding GitHub issue for each of those tests.

@azharcodeit Would you be willing to take this issue on?

**Comment by azharcodeit** [comment]
@mrobinson, sounds great! I am absolutely willing to do this

**Comment by mrobinson** [comment]
> @mrobinson, sounds great! I am absolutely willing to do this

Great! Thanks!
