### ISSUE TITLE
Catch issue title updates

### ISSUE THREAD

**Issue by Manishearth** [servo/intermittent-tracker#2]
Issues like https://github.com/servo/servo/issues/13919 have a list of similar tests in the title and the list often grows. The tracker does not notice these updates. It should.

**Comment by jdm** [comment]
The tracker has code to do this already. There was a bug regarding this that was fixed in the most recent commit, but maybe we haven't restarted the tracker since merging the PR to update it?

**Comment by Manishearth** [comment]
Probably. Also it's possible that the database contained outdated info for the edited bugs before the edit tracking was added.
